export const countryMap = {
  'GR': { lang: 'el', name: '希腊', en: 'Greece' },
  'NL': { lang: 'nl', name: '荷兰', en: 'Netherlands' },
  'BE': { lang: 'de', name: '比利时', en: 'Belgium' },
  'FR': { lang: 'fr', name: '法国', en: 'France' },
  'MC': { lang: 'fr', name: '摩纳哥', en: 'Monaco' },
  'AD': { lang: 'ca', name: '安道尔', en: 'Andorra' },
  'ES': { lang: 'eu', name: '西班牙', en: 'Spain' },
  'HU': { lang: 'hu', name: '匈牙利', en: 'Hungary' },
  'BA': { lang: 'sr', name: '波斯尼亚和黑塞哥维那', en: 'Bosnia and Herzegovina' },
  'HR': { lang: 'hr', name: '克罗地亚', en: 'Croatia' },
  'RS': { lang: 'sr', name: '塞尔维亚', en: 'Serbia' },
  'IT': { lang: 'fur', name: '意大利', en: 'Italy' },
  'RO': { lang: 'ro', name: '罗马尼亚', en: 'Romania' },
  'CH': { lang: 'rm', name: '瑞士', en: 'Switzerland' },
  'CZ': { lang: 'cs', name: '捷克', en: 'Czech Republic' },
  'SK': { lang: 'sk', name: '斯洛伐克', en: 'Slovakia' },
  'AT': { lang: 'en', name: '奥地利', en: 'Austria' },
  'GB': { lang: 'cy', name: '英国', en: 'United Kingdom' },
  'DK': { lang: 'en', name: '丹麦', en: 'Denmark' },
  'SE': { lang: 'se', name: '瑞典', en: 'Sweden' },
  'NO': { lang: 'nn', name: '挪威', en: 'Norway' },
  'FI': { lang: 'fi', name: '芬兰', en: 'Finland' },
  'LT': { lang: 'lt', name: '立陶宛', en: 'Lithuania' },
  'LV': { lang: 'lv', name: '拉脱维亚', en: 'Latvia' },
  'EE': { lang: 'et', name: '爱沙尼亚', en: 'Estonia' },
  'RU': { lang: 'os', name: '俄罗斯', en: 'Russia' },
  'UA': { lang: 'uk', name: '乌克兰', en: 'Ukraine' },
  'BY': { lang: 'be', name: '白俄罗斯', en: 'Belarus' },
  'MD': { lang: 'ru', name: '摩尔多瓦', en: 'Moldova' },
  'PL': { lang: 'pl', name: '波兰', en: 'Poland' },
  'DE': { lang: 'hsb', name: '德国', en: 'Germany' },
  'GI': { lang: 'en', name: '直布罗陀', en: 'Gibraltar' },
  'PT': { lang: 'pt', name: '葡萄牙', en: 'Portugal' },
  'LU': { lang: 'lb', name: '卢森堡', en: 'Luxembourg' },
  'IE': { lang: 'en', name: '爱尔兰', en: 'Ireland' },
  'IS': { lang: 'is', name: '冰岛', en: 'Iceland' },
  'AL': { lang: 'sq', name: '阿尔巴尼亚', en: 'Albania' },
  'MT': { lang: 'en', name: '马耳他', en: 'Malta' },
  'CY': { lang: 'en', name: '塞浦路斯', en: 'Cyprus' },
  'GE': { lang: 'os', name: '格鲁吉亚', en: 'Georgia' },
  'AM': { lang: 'hy', name: '亚美尼亚', en: 'Armenia' },
  'BG': { lang: 'bg', name: '保加利亚', en: 'Bulgaria' },
  'TR': { lang: 'tr', name: '土耳其', en: 'Turkey' },
  'FO': { lang: 'fo', name: '法罗群岛', en: 'Faroe Islands' },
  'GL': { lang: 'da', name: '格陵兰', en: 'Greenland' },
  'SM': { lang: 'it', name: '圣马力诺', en: 'San Marino' },
  'SI': { lang: 'en', name: '斯洛文尼亚', en: 'Slovenia' },
  'MK': { lang: 'mk', name: '北马其顿', en: 'North Macedonia' },
  'LI': { lang: 'gsw', name: '列支敦士登', en: 'Liechtenstein' },
  'ME': { lang: 'sr', name: '黑山', en: 'Montenegro' },
  'CA': { lang: 'en', name: '加拿大', en: 'Canada' },
  'PM': { lang: 'fr', name: '圣皮埃尔和密克隆', en: 'Saint Pierre and Miquelon' },
  'US': { lang: 'en', name: '美国', en: 'United States' },
  'PR': { lang: 'en', name: '波多黎各', en: 'Puerto Rico' },
  'VI': { lang: 'en', name: '美属维尔京群岛', en: 'U.S. Virgin Islands' },
  'MX': { lang: 'es', name: '墨西哥', en: 'Mexico' },
  'JM': { lang: 'en', name: '牙买加', en: 'Jamaica' },
  'MQ': { lang: 'fr', name: '马提尼克', en: 'Martinique' },
  'BB': { lang: 'en', name: '巴巴多斯', en: 'Barbados' },
  'AG': { lang: 'en', name: '安提瓜和巴布达', en: 'Antigua and Barbuda' },
  'KY': { lang: 'en', name: '开曼群岛', en: 'Cayman Islands' },
  'VG': { lang: 'en', name: '英属维尔京群岛', en: 'British Virgin Islands' },
  'BM': { lang: 'en', name: '百慕大', en: 'Bermuda' },
  'GD': { lang: 'en', name: '格林纳达', en: 'Grenada' },
  'MS': { lang: 'en', name: '蒙特塞拉特', en: 'Montserrat' },
  'KN': { lang: 'en', name: '圣基茨和尼维斯', en: 'Saint Kitts and Nevis' },
  'LC': { lang: 'en', name: '圣卢西亚', en: 'Saint Lucia' },
  'VC': { lang: 'en', name: '圣文森特和格林纳丁斯', en: 'Saint Vincent and the Grenadines' },
  'CW': { lang: 'nl', name: '库拉索', en: 'Curaçao' },
  'AW': { lang: 'nl', name: '阿鲁巴', en: 'Aruba' },
  'BS': { lang: 'en', name: '巴哈马', en: 'Bahamas' },
  'AI': { lang: 'en', name: '安圭拉', en: 'Anguilla' },
  'DM': { lang: 'en', name: '多米尼克', en: 'Dominica' },
  'CU': { lang: 'es', name: '古巴', en: 'Cuba' },
  'DO': { lang: 'es', name: '多米尼加', en: 'Dominican Republic' },
  'HT': { lang: 'fr', name: '海地', en: 'Haiti' },
  'TT': { lang: 'en', name: '特立尼达和多巴哥', en: 'Trinidad and Tobago' },
  'TC': { lang: 'en', name: '特克斯和凯科斯群岛', en: 'Turks and Caicos Islands' },
  'AZ': { lang: 'az', name: '阿塞拜疆', en: 'Azerbaijan' },
  'KZ': { lang: 'kk', name: '哈萨克斯坦', en: 'Kazakhstan' },
  'BT': { lang: 'dz', name: '不丹', en: 'Bhutan' },
  'IN': { lang: 'hi', name: '印度', en: 'India' },
  'PK': { lang: 'pa', name: '巴基斯坦', en: 'Pakistan' },
  'AF': { lang: 'uz', name: '阿富汗', en: 'Afghanistan' },
  'LK': { lang: 'si', name: '斯里兰卡', en: 'Sri Lanka' },
  'MM': { lang: 'my', name: '缅甸', en: 'Myanmar' },
  'LB': { lang: 'ar', name: '黎巴嫩', en: 'Lebanon' },
  'JO': { lang: 'ar', name: '约旦', en: 'Jordan' },
  'SY': { lang: 'ar', name: '叙利亚', en: 'Syria' },
  'IQ': { lang: 'ar', name: '伊拉克', en: 'Iraq' },
  'KW': { lang: 'ar', name: '科威特', en: 'Kuwait' },
  'SA': { lang: 'ar', name: '沙特阿拉伯', en: 'Saudi Arabia' },
  'YE': { lang: 'ar', name: '也门', en: 'Yemen' },
  'OM': { lang: 'ar', name: '阿曼', en: 'Oman' },
  'AE': { lang: 'ar', name: '阿联酋', en: 'United Arab Emirates' },
  'PS': { lang: 'ar', name: '巴勒斯坦', en: 'Palestine' },
  'BH': { lang: 'ar', name: '巴林', en: 'Bahrain' },
  'QA': { lang: 'ar', name: '卡塔尔', en: 'Qatar' },
  'MN': { lang: 'mn', name: '蒙古', en: 'Mongolia' },
  'NP': { lang: 'ne', name: '尼泊尔', en: 'Nepal' },
  'IR': { lang: 'mzn', name: '伊朗', en: 'Iran' },
  'UZ': { lang: 'uz', name: '乌兹别克斯坦', en: 'Uzbekistan' },
  'KG': { lang: 'ky', name: '吉尔吉斯斯坦', en: 'Kyrgyzstan' },
  'JP': { lang: 'ja', name: '日本', en: 'Japan' },
  'KR': { lang: 'ko', name: '韩国', en: 'South Korea' },
  'VN': { lang: 'vi', name: '越南', en: 'Vietnam' },
  'HK': { lang: 'zh', name: '香港', en: 'Hong Kong' },
  'MO': { lang: 'en', name: '澳门', en: 'Macao' },
  'KH': { lang: 'km', name: '柬埔寨', en: 'Cambodia' },
  'LA': { lang: 'lo', name: '老挝', en: 'Laos' },
  'CN': { lang: 'zh', name: '中国', en: 'China' },
  'TW': { lang: 'zh', name: '台湾', en: 'Taiwan' },
  'KP': { lang: 'ko', name: '朝鲜', en: 'North Korea' },
  'BD': { lang: 'bn', name: '孟加拉国', en: 'Bangladesh' },
  'MY': { lang: 'en', name: '马来西亚', en: 'Malaysia' },
  'AU': { lang: 'en', name: '澳大利亚', en: 'Australia' },
  'ID': { lang: 'in', name: '印度尼西亚', en: 'Indonesia' },
  'TL': { lang: 'pt', name: '东帝汶', en: 'Timor-Leste' },
  'PH': { lang: 'en', name: '菲律宾', en: 'Philippines' },
  'TH': { lang: 'th', name: '泰国', en: 'Thailand' },
  'SG': { lang: 'en', name: '新加坡', en: 'Singapore' },
  'BN': { lang: 'ms', name: '文莱', en: 'Brunei' },
  'NZ': { lang: 'en', name: '新西兰', en: 'New Zealand' },
  'MP': { lang: 'en', name: '北马里亚纳群岛', en: 'Northern Mariana Islands' },
  'GU': { lang: 'en', name: '关岛', en: 'Guam' },
  'NR': { lang: 'en', name: '瑙鲁', en: 'Nauru' },
  'PG': { lang: 'en', name: '巴布亚新几内亚', en: 'Papua New Guinea' },
  'TO': { lang: 'en', name: '汤加', en: 'Tonga' },
  'SB': { lang: 'en', name: '所罗门群岛', en: 'Solomon Islands' },
  'VU': { lang: 'fr', name: '瓦努阿图', en: 'Vanuatu' },
  'FJ': { lang: 'en', name: '斐济', en: 'Fiji' },
  'WF': { lang: 'fr', name: '瓦利斯和富图纳', en: 'Wallis and Futuna' },
  'AS': { lang: 'en', name: '美属萨摩亚', en: 'American Samoa' },
  'KI': { lang: 'en', name: '基里巴斯', en: 'Kiribati' },
  'NC': { lang: 'fr', name: '新喀里多尼亚', en: 'New Caledonia' },
  'PF': { lang: 'fr', name: '法属波利尼西亚', en: 'French Polynesia' },
  'CK': { lang: 'en', name: '库克群岛', en: 'Cook Islands' },
  'WS': { lang: 'en', name: '萨摩亚', en: 'Samoa' },
  'FM': { lang: 'en', name: '密克罗尼西亚', en: 'Micronesia' },
  'MH': { lang: 'en', name: '马绍尔群岛', en: 'Marshall Islands' },
  'PW': { lang: 'en', name: '帕劳', en: 'Palau' },
  'NU': { lang: 'en', name: '纽埃', en: 'Niue' },
  'EG': { lang: 'ar', name: '埃及', en: 'Egypt' },
  'DZ': { lang: 'kab', name: '阿尔及利亚', en: 'Algeria' },
  'MA': { lang: 'fr', name: '摩洛哥', en: 'Morocco' },
  'TN': { lang: 'fr', name: '突尼斯', en: 'Tunisia' },
  'LY': { lang: 'ar', name: '利比亚', en: 'Libya' },
  'GM': { lang: 'en', name: '冈比亚', en: 'Gambia' },
  'SN': { lang: 'ff', name: '塞内加尔', en: 'Senegal' },
  'MR': { lang: 'ar', name: '毛里塔尼亚', en: 'Mauritania' },
  'ML': { lang: 'khq', name: '马里', en: 'Mali' },
  'GN': { lang: 'ff', name: '几内亚', en: 'Guinea' },
  'CI': { lang: 'fr', name: '科特迪瓦', en: 'Ivory Coast' },
  'BF': { lang: 'fr', name: '布基纳法索', en: 'Burkina Faso' },
  'NE': { lang: 'dje', name: '尼日尔', en: 'Niger' },
  'TG': { lang: 'fr', name: '多哥', en: 'Togo' },
  'BJ': { lang: 'fr', name: '贝宁', en: 'Benin' },
  'MU': { lang: 'fr', name: '毛里求斯', en: 'Mauritius' },
  'LR': { lang: 'vai', name: '利比里亚', en: 'Liberia' },
  'SL': { lang: 'en', name: '塞拉利昂', en: 'Sierra Leone' },
  'GH': { lang: 'en', name: '加纳', en: 'Ghana' },
  'NG': { lang: 'ha', name: '尼日利亚', en: 'Nigeria' },
  'TD': { lang: 'ar', name: '乍得', en: 'Chad' },
  'CF': { lang: 'sg', name: '中非', en: 'Central African Republic' },
  'CM': { lang: 'kkj', name: '喀麦隆', en: 'Cameroon' },
  'CV': { lang: 'kea', name: '佛得角', en: 'Cape Verde' },
  'ST': { lang: 'pt', name: '圣多美和普林西比', en: 'São Tomé and Príncipe' },
  'GQ': { lang: 'es', name: '赤道几内亚', en: 'Equatorial Guinea' },
  'GA': { lang: 'fr', name: '加蓬', en: 'Gabon' },
  'CG': { lang: 'ln', name: '刚果（布）', en: 'Congo (Brazzaville)' },
  'CD': { lang: 'fr', name: '刚果（金）', en: 'Congo (Kinshasa)' },
  'AO': { lang: 'ln', name: '安哥拉', en: 'Angola' },
  'GW': { lang: 'pt', name: '几内亚比绍', en: 'Guinea-Bissau' },
  'SC': { lang: 'en', name: '塞舌尔', en: 'Seychelles' },
  'SD': { lang: 'en', name: '苏丹', en: 'Sudan' },
  'RW': { lang: 'en', name: '卢旺达', en: 'Rwanda' },
  'ET': { lang: 'am', name: '埃塞俄比亚', en: 'Ethiopia' },
  'SO': { lang: 'ar', name: '索马里', en: 'Somalia' },
  'DJ': { lang: 'so', name: '吉布提', en: 'Djibouti' },
  'KE': { lang: 'guz', name: '肯尼亚', en: 'Kenya' },
  'TZ': { lang: 'kde', name: '坦桑尼亚', en: 'Tanzania' },
  'UG': { lang: 'lg', name: '乌干达', en: 'Uganda' },
  'BI': { lang: 'fr', name: '布隆迪', en: 'Burundi' },
  'MZ': { lang: 'seh', name: '莫桑比克', en: 'Mozambique' },
  'ZM': { lang: 'bem', name: '赞比亚', en: 'Zambia' },
  'MG': { lang: 'en', name: '马达加斯加', en: 'Madagascar' },
  'RE': { lang: 'fr', name: '留尼汪', en: 'Réunion' },
  'SZ': { lang: 'en', name: '斯威士兰', en: 'Eswatini' },
  'KM': { lang: 'ar', name: '科摩罗', en: 'Comoros' },
  'ZA': { lang: 'af', name: '南非', en: 'South Africa' },
  'ER': { lang: 'en', name: '厄立特里亚', en: 'Eritrea' },
  'BZ': { lang: 'en', name: '伯利兹', en: 'Belize' },
  'GT': { lang: 'es', name: '危地马拉', en: 'Guatemala' },
  'SV': { lang: 'es', name: '萨尔瓦多', en: 'El Salvador' },
  'HN': { lang: 'es', name: '洪都拉斯', en: 'Honduras' },
  'NI': { lang: 'es', name: '尼加拉瓜', en: 'Nicaragua' },
  'CR': { lang: 'es', name: '哥斯达黎加', en: 'Costa Rica' },
  'PA': { lang: 'es', name: '巴拿马', en: 'Panama' },
  'PE': { lang: 'qu', name: '秘鲁', en: 'Peru' },
  'AR': { lang: 'es', name: '阿根廷', en: 'Argentina' },
  'BR': { lang: 'pt', name: '巴西', en: 'Brazil' },
  'CL': { lang: 'es', name: '智利', en: 'Chile' },
  'CO': { lang: 'es', name: '哥伦比亚', en: 'Colombia' },
  'VE': { lang: 'es', name: '委内瑞拉', en: 'Venezuela' },
  'BO': { lang: 'qu', name: '玻利维亚', en: 'Bolivia' },
  'GY': { lang: 'en', name: '圭亚那', en: 'Guyana' },
  'EC': { lang: 'es', name: '厄瓜多尔', en: 'Ecuador' },
  'GF': { lang: 'fr', name: '法属圭亚那', en: 'French Guiana' },
  'PY': { lang: 'es', name: '巴拉圭', en: 'Paraguay' },
  'SR': { lang: 'nl', name: '苏里南', en: 'Suriname' },
  'UY': { lang: 'es', name: '乌拉圭', en: 'Uruguay' },
  'FK': { lang: 'en', name: '福克兰群岛', en: 'Falkland Islands' }
}

// 根据国家代码获取英文名称
export const getCountryEnglishName = (code) => {
  const info = countryMap[code]
  return info ? info.en : code
}
